Skip a problematic test on 1.6 (#848)
On Windows, Julia 1.6, the signatures test fails with

```
Base signatures: Error During Test at D:\a\Revise.jl\Revise.jl\test\runtests.jl:3851
  Got exception outside of a @test
  LoadError: invalid redefinition of constant RandomDevice
  Stacktrace:
   [1] do_assignment!(frame::Frame, lhs::Any, rhs::Any)
     @ JuliaInterpreter C:\Users\runneradmin\.julia\packages\JuliaInterpreter\cxlKp\src\interpret.jl:352
  in expression starting at D:\a\Revise.jl\Revise.jl\test\sigtest.jl:106
```

Since this only happens on a soon-to-be-unsupported Julia release, let's just ignore the test.