make REPL AST transform work when `active_module` is set to `Core.Compiler` (#751)
Otherwise REPL will result in the following error since `isempty` is
resolved within `Core.Compiler` context module:
```julia
Core.Compiler) julia> 42
ERROR: MethodError: no method matching iterate(::Base.Set{Tuple{Revise.PkgData, String}})
You may have intended to import Base.iterate

Closest candidates are:
  iterate(::MethodSpecializations)
   @ Core reflection.jl:1146
  iterate(::MethodSpecializations, ::Nothing)
   @ Core reflection.jl:1152
  iterate(::MethodSpecializations, ::Int64)
   @ Core reflection.jl:1153
  ...

Stacktrace:
 [1] isempty(itr::Base.Set{Tuple{Revise.PkgData, String}})
   @ Core.Compiler ./essentials.jl:952
 [2] top-level scope
   @ none:1
```